// <auto-generated />
using System;
using Ecommerce_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250801073111_SeedCategoryData")]
    partial class SeedCategoryData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce_Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ELEC",
                            CreatedDate = new DateTime(2025, 8, 1, 12, 31, 11, 209, DateTimeKind.Local).AddTicks(9058),
                            Description = "Devices and gadgets",
                            Name = "Electronics",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Code = "JEWEL",
                            CreatedDate = new DateTime(2025, 8, 1, 12, 31, 11, 209, DateTimeKind.Local).AddTicks(9074),
                            Description = "Jewellery and accessories",
                            Name = "Jewellery",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Code = "CLOTH",
                            CreatedDate = new DateTime(2025, 8, 1, 12, 31, 11, 209, DateTimeKind.Local).AddTicks(9076),
                            Description = "Apparel and garments",
                            Name = "Clothing",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Code = "WOMEN",
                            CreatedDate = new DateTime(2025, 8, 1, 12, 31, 11, 209, DateTimeKind.Local).AddTicks(9077),
                            Description = "Women's clothing and accessories",
                            Name = "Women",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Code = "MEN",
                            CreatedDate = new DateTime(2025, 8, 1, 12, 31, 11, 209, DateTimeKind.Local).AddTicks(9079),
                            Description = "Men's clothing and accessories",
                            Name = "Men",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
